blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (home, register_view, login_view, logout_view, contact_mail,
                    PostsList, post_view, create_post_view, post_update_view, post_delete_view,
                    AuthorsList, author_view, author_update_view, AuthorPostsList,
                    dashboard_view, profile_view, settings_view,
                    )

app_name = 'blog'
urlpatterns = [
    path('', home, name='home'),

    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),

    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='blog/password_change_form.html'),
         name='password_change'
         ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(template_name='blog/password_change_done.html'),
        name='password_change_done'
    ),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='blog/password_reset_form.html'),
         name='reset_password'),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='blog/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='blog/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name='blog/password_reset_complete.html'),
        name='password_reset_complete'
    ),

    path('dashboard/', dashboard_view, name='dashboard'),
    path('profile/', profile_view, name='user-profile'),
    path('settings/', settings_view, name='user-settings'),
    path('my-posts/', AuthorPostsList.as_view(), name='my-posts'),

    path('posts/', PostsList.as_view(), name='posts'),
    path('post/<str:slug>/', post_view, name='post'),
    path('create-post', create_post_view, name='create-post'),
    path('delete-post/<str:slug>/', post_delete_view, name='delete-post'),
    path('update-post/<str:slug>/', post_update_view, name='update-post'),

    path('authors/', AuthorsList.as_view(), name='authors'),
    path('author/<str:slug>/', author_view, name='author'),
    path('update-author/<slug:slug>/', author_update_view, name='update-author'),

    path('contactus/', contact_mail, name='contactus'),

]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('', include('django.contrib.auth.urls')),
]
from django.conf import  settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import ContactUs, Comment, Post, Author
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email']

class CreatePostForm(forms.ModelForm):
    content = forms.Textarea()
    content = forms.Textarea()

    class Meta:
        model = Post
        fields = ['title', 'content', 'post_pic', 'slug',  'status' , 'privacy']
        widgets = {
            'content': forms.Textarea(attrs={'cols': 80, 'rows': 15}),

        }

class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea, label='Comment Message')
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = "__all__"

class UpdateAuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name',  'phone_no', 'email', 'address',  'photo' , 'about']

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import ContactUsForm, SignUpForm, CommentForm, CreatePostForm, UpdateAuthorForm
from django.core.mail import EmailMessage
from django.conf import settings
from .models import Post, Author, Comment, Public_Post, Author_Post
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .decorators import unauthenticated_user
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

@unauthenticated_user
def register_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            name = request.POST.get('username')
            messages.success(request, f'{name} account created successfully.')
            return redirect('blog:login')
        else:
            messages.error(request, 'Please Correct the errors!')
    else:
        form = SignUpForm()
    context = {'form': form}
    return render(request, 'blog/register.html', context)

@unauthenticated_user
def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, f"Welcome {user.username.upper()}! You are logged in.")
            return redirect('blog:dashboard')
        else:
            messages.info(request, 'Username OR Password is incorrect!')
    context = {}
    return render(request, 'blog/new_login.html', context)


def logout_view(request):
    logout(request)
    messages.success(request, "Thanks for using our web services. You are logged out.")
    return redirect('blog:login')


def home(request):
    context = {}
    return render(request, 'blog/index.html', context)


@login_required(login_url='blog:login')
def dashboard_view(request):
    posts = Post.objects.all()
    comments = Comment.objects.all()

    my_posts = posts.filter(creator=request.user.author)
    my_total_posts = my_posts.count()
    my_total_published_posts = my_posts.filter(status='P').count()
    my_total_draft_posts = my_posts.filter(status='D').count()
    # my_total_public_posts = my_posts.filter(privacy='Public').count()
    my_total_public_posts = my_posts.filter(status='P', privacy='Public').count()
    my_total_private_posts = my_posts.filter(privacy='Private').count()

    latest_posts = posts.order_by('-published_date')[:5:]
    top_posts = []
    for post in posts:
        com_count = post.comment_set.all().count()
        post_title = post.title
        t = (com_count, post_title)
        top_posts.append(t)
    top_posts.sort(reverse=True)
    most_commented = []
    context = {
        'latest_posts': latest_posts,
        'comments': comments,
        'most_commented': most_commented,
        'my_total_posts': my_total_posts,
        'my_total_public_posts': my_total_public_posts,
        'my_total_private_posts': my_total_private_posts,
        'my_total_published_posts': my_total_published_posts,
        'my_total_draft_posts': my_total_draft_posts,
    }

    return render(request, 'blog/user-dashboard.html', context)


@login_required(login_url='blog:login')
def profile_view(request):
    author = Author.objects.get(slug=request.user)
    post_list = author.post_set.all()

    total_posts = post_list.count()
    recent_posts = post_list.order_by('-published_date')[:5:]

    context = {'post_list': post_list,
               'author': author,
               'total_posts': total_posts,
               'recent_posts': recent_posts,
               }
    return render(request, 'blog/user_profile.html', context)


@login_required(login_url='blog:login')
def settings_view(request):
    author = Author.objects.get(slug=request.user)
    context = {'author': author}
    return render(request, 'blog/settings.html', context)


class AuthorPostsList(ListView):
    model = Author_Post
    paginate_by = 5
    template_name =  "blog/my-posts-list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Author_Post.objects.all().filter(creator=self.request.user.author )
        print(Author_Post.objects.all().filter(creator=self.request.user.author ).count())
        return context


class PostsList(ListView):
    model = Public_Post
    paginate_by = 10
    template_name = 'blog/post_list.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Public_Post.objects.all()
        print(Public_Post.objects.all().count())
        return context


def post_view(request, slug):
    post = Post.objects.get(slug=slug)
    comments = post.comment_set.filter(active=True)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if request.user.is_authenticated:
            if form.is_valid():
                new_comment = form.save(commit=False)
                new_comment.post = post
                new_comment.save()
                messages.success(request, f"Your comment submitted successfully.")
                return redirect('blog:post', slug=post.slug)
        else:
            messages.error(request, f"Please SignIn to  comment on posts!")
            return redirect("blog:login")

    else:
        form = CommentForm()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'blog/post_detail.html', context)


@login_required(login_url='blog:login')
def create_post_view(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)

        print("validating of form starting")
        if form.is_valid:
            post = form.save(commit=False)
            post.creator = Author.objects.get(name=request.user)
            post.save()
            return redirect('blog:my-posts')
    form = CreatePostForm()
    context = {'form': form}
    return render(request, 'blog/post_form.html', context)


@login_required(login_url='blog:login')
def post_update_view(request,slug):
    try:
        post = Post.objects.get(slug=slug)
    except :
        messages.error(request, "The requested post is not Found.")
        return redirect("blog:posts")
    if post.creator == request.user.author:
        form = CreatePostForm(instance=post)
        context = {"form": form}
        return render(request, 'blog/post_form.html', context)
    else:
        messages.error(request, "You're are not allowed to view the requested page! You can update your Posts.")
        return redirect('blog:my-posts')


@login_required(login_url='blog:login')
def post_delete_view(request,slug):
    post = Post.objects.get(slug=slug)
    if post.creator == request.user.author or request.user.is_superuser:
        if request.method == 'POST':
            post.delete()
            return redirect('blog:my-posts')
        context = {'post':post}
        return render(request, 'blog/post_confirm_delete.html', context)
    else:
        messages.error(request, "You're are not allowed to delete Someone's Post! Here's your posts list.")
        return redirect('blog:my-posts')



class AuthorsList(ListView):
    model = Author
    paginate_by = 6

from django.db.models import Q
def author_view(request, slug):
    author = Author.objects.get(slug=slug)
    post_list = author.post_set.filter(~Q(status='D'),~Q(privacy='Private'))
    recent_posts = post_list.order_by('-published_date')[:5:]
    total_posts = post_list.count()
    context = {'post_list': post_list,
               'author': author,
               'total_posts': total_posts,
               'recent_posts': recent_posts,
               }
    return render(request, 'blog/author_detail.html', context)


@login_required(login_url='blog:login')
def author_update_view(request, slug):
    if slug == request.user.author.slug:
        author = Author.objects.get(slug=slug)
    else:
        messages.error(request, "You're are not allowed to view the requested page! You can update your profile.")
        author = Author.objects.get(slug=request.user.author.slug)

    if request.method == "POST":
        form = form = UpdateAuthorForm(request.POST,request.FILES,instance=author)
        if form.is_valid():
            form.save()
            messages.success(request, "Profile updated successfully.")
            return redirect('blog:user-profile')
        else:
            messages.error(request, "plaease correct the errors")

    form = UpdateAuthorForm(instance=author)
    context = {"form" : form}
    return render(request, 'blog/author_form.html', context)


def contact_mail(request):
    if request.method == "POST":
        form = ContactUsForm(request.POST)
        if form.is_valid():
            name = request.POST.get('name')
            mail = request.POST.get('email')
            sub = request.POST.get('subject')
            meassage = request.POST.get('body')

            email = EmailMessage(
                'Hello! You got a mail from ' + "mail",
                "Name : " + str(name) + '\n'
                    f"Email : {str(mail)} \n"
                    f"Subject : {str(sub)} \n"
                    f"Meassage : {str(meassage)} \n",
                settings.EMAIL_HOST_USER,  # 'from@example.com',
                ['nagaraj015973@gmail.com', 'love.haters.fully@gmail.com'],  # to@example.com',
            )
            email.send(fail_silently=False)
            form.save()
            return redirect('blog:home')
    else:

blog/templates/blog/author_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
<link href="https://fonts.googleapis.com/css2?family=Trade+Winds&display=swap" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">

{% block content %}

<div class="container-fluid ">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-2 offset-auto mb-5">
        <div class="col col-12 col-sm-12 col-md-6 col-lg-5">
            <div class="card text-canter pl-5" id="mailus">
                <h5 class="card-header text-center"><span
                        style="font-weight:900;font-family: 'Girassol', cursive;letter-spacing:2px;"> Update Profile </span>
                </h5>
                <div class="card-body text-left pl-5 ">
                    <form method="POST" enctype="multipart/form-data" class="form-group">
                        {% csrf_token %}
                        {{form|crispy}}

                        <input type="submit" name="" value="Update Details" class="btn btn-primary btn-md">
                    </form>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/author_list.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/posts.css' %}">

{% block title %} Authors List {% endblock title %}
{% block content %}
<div class="" id="stricky">
    <h4 class="card-header text-center" id="author-head"><b>Authors list</b></h4>
</div>

<div class="container">
    <div class="row">
        {% if author_list %}
        {% for author in author_list %}
        <div class="col col-12 col-sm-6 col-md-4 col-lg-4 p-3">
            <div class="card m-auto mt-5 mb-5" style="width: 18rem;">
                <h5 class="card-header text-center pt-3 " id="p-header">{{author.name|upper}} </h5>
                <img class="card-img-top" {% if author.photo %} src="{{author.photo.url}}" {% else %}
                     src="{% static 'images/default-user.jpg' %}" {% endif %} alt='{{author.name}}' height="250px"
                     width="250px" title="{{author.name}}"/>
                <div class="card-body">
                    <p class="card-text">{{author.name}}<br>{{author.dob}}</p>
                    <a href="{% url 'blog:author' author.slug %}" class="btn btn-primary">More about {{author.name}}</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="card-body text-center">
    <h4 class="alert" style="color:gold;"><b><i> No authors yet!</i></b></h4>
</div>
{% endif %}
<br>
{% if author_list %}
{% include 'blog/pagination.html' %}
{% endif %}
<br>


<br>
{% endblock %}

blog/templates/blog/carousel.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


<div class="container">
    <!--  <h2></h2>-->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <img src="{% static 'images/carousel1.jpg' %}" alt="Los Angeles" style="width:100%;">
            </div>

            <div class="item">
                <img src="{% static 'images/carousel2.jpg' %}" alt="Chicago" style="width:100%;">
            </div>

            <div class="item">
                <img src="{% static 'images/carousel3.jpg' %}" alt="New york" style="width:100%;">
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

blog/templates/blog/comments.html
{% load crispy_forms_tags %}

<style>
    #comment-form{
        color : #fff ;
        background-color : transparent;
    }
    #comments{
        color : #fff ;
        background-color : darkgreen;
        background-color : #000000;
    }

</style>

<div class="row">
    <div class="col col-md-4 offset-auto " id="comment-form">
        <h3 class="card-header">Leave a comment</h3>
        <div class="card-body ">
                <form method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                    <div class="text text-right">
                        <input type="submit" value="Submit" name="" class="btn btn-primary btn-sm">
                    </div>
                </form>
        </div>
    </div>
    <div class="col mb-5  m-3" id="comments">
        <div class="card-body  p-3 " >
            <h4>{{ comments.count }} comment{{ comments.count | pluralize }}</h4>
            {% if comments %}
            {% for comment in comments %}
            <p> <h6><span style="color:red;font-weight:900;">{{comment.name|title}}</span> commented <span style="color:silver;">{{comment.created_date|timesince}}</span>
            ago</h6>{{comment.body|linebreaks}} </p>
            {% endfor %}
            {% else %}
            <p>This post don't have any comments yet!</p>
            {% endif %}
        </div>
    </div>
</div>

blog/templates/blog/contactus.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
<link href="https://fonts.googleapis.com/css2?family=Trade+Winds&display=swap" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
{% block content %}

<div class="container-fluid ">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-2 offset-auto mb-5">
        <div class="col col-12 col-sm-12 col-md-6 col-lg-5">
            <div class="card text-canter pl-5" id="mailus">
                <h5 class="card-header text-center"> <span style="font-weight:900;font-family: 'Girassol', cursive;letter-spacing:2px;">Mail Us</span> </h5>
                <div class="card-body text-left pl-5 ">
                    <form method="POST" class="form-group">
                        {% csrf_token %}
                        {{form|crispy}}
                        <input type="submit" name="" val="Submit" class="btn btn-primary btn-md">
                    </form>
                    <br>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card" id="mailus">
                <h5 class="card-header text-center mb-5"> <span style="font-weight:900;font-family: 'Girassol', cursive;letter-spacing:2px;">Our Office Address</span> </h5>
                <div class="'card-body text-right pr-5 mr-5">
                    <div class="card-title pl-5 ml-5">
                        <address class="text-left ml-5 pl-5">

                            <a href="mailto:my@gmail.com">Krishna Bellamkonda</a>.<br>
                            Visit us at :<br>
                            Madhapur, Hyderabad, Telangana 500081<br>
                            our website : <a href="">krishna.com</a> <br>
                            Box 564, Disneyland<br>
                            USA
                        </address>
                    </div>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d7613.006847775043!2d78.38296138623045!3d17.435602736162725!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb339ecd8cf9b2ce5!2sZenQ!5e0!3m2!1sen!2sin!4v1587039628572!5m2!1sen!2sin"
                            width="70%" height="250" frameborder="0" style="border:3px groove transparent;"
                            allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>

                </div>

            </div>

        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/index.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">

{% block title %} Krishna Blog User Page {% endblock title %}
{% block content %}
<div class="container ">
    <div class="row mb-5">
        <div class="col mb-5">
            <div class="welcome" style="color:#fff;">
                <h3 style=" font-family: 'Trade Winds', cursive;border-bottom:5px double green;padding-bottom:5px;color:#fff;">
                    welcome 2 Krishna Blog :</h3>
                <div style="padding:0 2% 0 2%;">
                    <p>Money isn't money
                        anymore. <br>
                        Time doesn't feel like time anymore.<br>
                        Your sense of community, it's
                        evaporated, too, or it's turned into something you visit at 2 A.M. on a website.</p>
                    <br>
                    <p> You can get inspired from a magazine. yes, but you can also be inspired from a website. Connect
                        with us and be in
                        touch with our website. You can find many posts which wil help you in many ways.
                    </p>
                </div>
            </div>
            <br>

        </div>
        <br><br>
    </div>
</div>


{% endblock %}

blog/templates/blog/login.html
<form method="POST">
    {% csrf_token %}
<div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
    aria-hidden="true" style="background-color:silver;">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header text-center">
            <h4 class="modal-title w-100 font-weight-bold" style="color:green; font-variant: small-caps;">login</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body mx-3">
            <div class="md-form mb-5">
              <i class="fas fa-user prefix grey-text"></i> &nbsp&nbsp&nbsp&nbsp&nbsp
              {{form2.name}}
            </div>
            <div class="md-form mb-4" >
              <i class="fas fa-lock prefix grey-text"></i> &nbsp&nbsp&nbsp&nbsp&nbsp
              {{form2.pswd}}

            </div>

          </div>
          <div class="modal-footer d-flex justify-content-center">
            <button role="submit" class="btn btn-outline-primary btn-md" style="letter-spacing:2px; font-weight:900;">LogIn</button>
          </div>
        </div>
      </div>
    </div>

    <div class="text-center">
    <a href="" class="nav-link" data-toggle="modal" data-target="#modalLoginForm">Login</a>
    </div>
</form>

blog/templates/blog/my-posts-list.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/posts.css' %}">

{% block title %} {{ request.user.username | title }} Posts List {% endblock title %}
{% block content %}
<div class="" id="sticky" >
    <h4 class="card-header text-center ">My Posts</h4>
</div>
<div class="container">
    <div class="row">
        {% if object_list %}
        <div class="row row-col-md-1">
            <div class="col col-12 col-sm-12 col-md-12 col-lg-12 ">
                 {% for post in object_list %}
                <div class="card mt-4" style="max-width:100%;">
                    <h5 class="card-header pt-3 pl-3 " id="p-header"> Post : <b>{{post.title}}</b></h5>
                    <div class="card-title pl-5 pt-3 mb-0 pb-0" id="p-title">
                        <h6> Posted by <span id="pc-name"">{{post.creator}}</span> on <span id="p-date"">{{post.published_date}}</span>
                            <br>Last update : <span id="p-date">{{post.updated_date|timesince}}</span> ago
                        </h6>
                    </div>
                    <div class="card-body mb-0 pb-0 pt-2 mt-0" id="p-body">
                        <div class="row">
                            <div class="col col-sm-2 col-md-2">

                                <img class="rounded-circle" {% if post.post_pic %} src="{{post.post_pic.url}}" {% else %} src="{% static 'images/image-comingsoon.png' %}" {% endif %} alt='{{post.name}}'
                                     width="100px" height="100px" title="{{post.title}}">
                            </div>
                            <div class="col col-9"> {{post.content|truncatewords:45}}
                            </div>
                        </div>
                        <div class="text-right mr-5 pr-5 mb-4 pt-0">

                            <a href="{% url 'blog:post' post.slug %}" class="btn btn-info btn-md" id="btn-post">Read
                                More...</a>
                            {% if user.is_authenticated %}
                            <a href="{% url 'blog:update-post' post.slug %}" class="btn btn-warning btn-md" id="btn-post">Update
                                Post</a>
                            <a href="{% url 'blog:delete-post' post.slug %}" class="btn btn-danger btn-md" id="btn-post">Delete
                                Post</a>
                            {% endif %}

                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% else %}
        <div class="card-body text-center">
            <h4 class="alert" style="color:gold;"><b><i>You have not posted any posts yet!</i></b></h4>
            <a href="{% url 'blog:create-post' %}" class="btn btn-primary btn-md" style="font-size:14px;font-weight:700;letter-spacing:1.5px;">Create a Post</a>
        </div>
        {% endif %}
    </div>
</div>
<br>
<!--{% if object_list %}-->
<!--    {% include 'blog/pagination.html' %}-->
<!--{% endif %}-->
<br>
{% endblock %}

blog/templates/blog/pagination.html
<style>
    #pagination{
            background-color : olive;
             font-weight : 900;
        }
    .current{
        color : gold;
    }
    #page{
        color: linen;
    }
    .step-links a:hover{
        background-color : black ;
		padding : 3px;
		margin-left : 10px;
    }
</style>
<div class="text-center p-2 mb-0 pb-0 " id="pagination">
			    <span class="step-links">
			        {% if page_obj.has_previous %}
			            <a href="?page=1" id="page">  <span>&laquo;&laquo;  First</span></a>
			            <a href="?page={{ page_obj.previous_page_number }}" id="page"> &laquo; Previous</a>
			        {% endif %}
			        <span class="current">
			            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
			        </span>
			        {% if page_obj.has_next %}
			            <a href="?page={{ page_obj.next_page_number }}" id="page"> Next &raquo;</a>
			            <a href="?page={{ page_obj.paginator.num_pages }}" id="page">Last <span>&raquo;&raquo; </span></a>
			        {% endif %}
			    </span>
</div>

blog/templates/blog/password_reset_complete.html
{% extends "blog/base.html" %}
{% load i18n %}


{% block title %}Krishna Blog - Password reset complete {% endblock %}


{% block content %}
<div class="container" style="color:#fff;letter-spacing:2px;">
    <div class="row m-5">
        <div class="col">
            <h4 class="card-header">Password reset complete</h4>
            <div class="card-body">

                <p>{% trans "Your password has been set. You may go ahead and log in now." %}</p>

                <!--<p><a href="{{ login_url }}">{% trans 'Log in' %}</a></p>-->
                <p><a href="{% url 'blog:login' %}" class="btn btn-primary btn-sm">Log in</a></p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/password_reset_done.html
{% extends "blog/base.html" %}
{% load i18n %}
{% load i18n static %}

{% block title %}Krishna Blog - Password reset sent {% endblock %}

{% block content %}

<div class="container" style="color:#fff;letter-spacing:2px;">
    <div class="row m-5">
        <div class="col">
            <h4 class="card-header">Password reset sent</h4>
            <div class="card-body">
                <p>We’ve emailed you instructions for setting your password, if an account exists with the
                    email you entered. You should receive them shortly.</p>

                <p>If you don’t receive an email, please make sure you’ve entered the address you registered
                    with, and check your spam folder.</p>

            </div>
        </div>
    </div>
</div>
{% endblock %}